[package]
name = "combined"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "true"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.17.0"
egui = "0.17.0"
tinyfiledialogs = "3.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
zip = "0.6.0"
image = "0.24.1"
async-std = "1.11.0"